### ISSUE TITLE
Orbital Period calculation

### ISSUE THREAD

**Issue by tpusch** [irskep/stellardream#1]
Just read your article on generating planets from Kepler data, thought it was really good and linked a lot of great sources!

Anyway, here's the c# code for calculating the orbital period of a child object around its parent, works for planets around a star or moons around a planet:
```c#
private const double GaussianGravConstant = .01720209895;

public static double CalculateOrbitalPeriod(double orbitalAu, double parentSolarMass, double childSolarMass) {
 var semiMajorAxisCubed = Math.Pow(orbitalAu, 3); //a^3

 var numerator = 4 * Math.Pow(Math.PI, 2); // 4 pi^2 

 var denominator = Math.Pow(GaussianGravConstant, 2) * (parentSolarMass + childSolarMass); //k^2 * Mtot
 
 var right = (numerator / denominator) * semiMajorAxisCubed; // P^2

 var periodInDays = Math.Sqrt(right);

 return periodInDays;
}
````

**Comment by irskep** [comment]
Thanks! I also got the answer from a Reddit comment and added it to the UI rather than the library: https://github.com/irskep/keplverse/blob/master/src/components/PlanetInfo.js#L65
